# Generated by Django 4.2.7 on 2023-11-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название должности')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(help_text='Фамилия сотрудника', max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(help_text='Имя сотрудника', max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(help_text='Отчество сотрудника', max_length=30, verbose_name='Отчество')),
                ('date_of_employment', models.DateField(verbose_name='Дата принятия на работу')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.position', verbose_name='Должность')),
            ],
            options={
                'ordering': ['surname', 'name'],
            },
        ),
    ]
